export const studentData = {
  student_profile: {
    student_id: "STU_0001",
    full_name: "Aarav Sharma",
    date_of_birth: "2010-06-15",
    location: "Bengaluru, India",
    school_name: "Green Valley High School",
    board: "CBSE",
    portfolio_slug: "aarav-sharma",
    profile_photo: "",
    contact: { email: "", phone: "", parent_contact: "" },
  },
  journey_summary: {
    tagline: "Curious learner passionate about science and leadership",
    philosophy: "Learning by doing and solving real-world problems",
    future_goals: ["Environmental Engineer", "Sustainability Researcher"],
    strengths: ["Analytical Thinking", "Leadership", "Creativity"],
    areas_of_interest: ["Science", "Technology", "Chess", "Public Speaking"],
  },
  academic_journey: [
    {
      grade: "Grade 5",
      year: "2020-2021",
      subjects: [
        { name: "Mathematics", score: 98, grade: "A+", teacher_feedback: "Excellent problem-solving skills" },
        { name: "Science", score: 95, grade: "A+", teacher_feedback: "Very curious and experimental mindset" },
        { name: "English", score: 90, grade: "A+", teacher_feedback: "Strong communicator" },
        { name: "Social Studies", score: 88, grade: "A", teacher_feedback: "Good analytical skills" },
      ],
      overall_percentage: 94.5,
      rank: "Top 3",
      attendance: "96%",
    },
    {
      grade: "Grade 6",
      year: "2021-2022",
      subjects: [
        { name: "Mathematics", score: 96, grade: "A+", teacher_feedback: "Outstanding computational thinking" },
        { name: "Science", score: 97, grade: "A+", teacher_feedback: "Natural scientist" },
        { name: "English", score: 92, grade: "A+", teacher_feedback: "Excellent vocabulary" },
        { name: "Social Studies", score: 85, grade: "A", teacher_feedback: "Curious and engaged" },
      ],
      overall_percentage: 92.5,
      rank: "Top 5",
      attendance: "98%",
    },
    {
      grade: "Grade 7",
      year: "2022-2023",
      subjects: [
        { name: "Mathematics", score: 99, grade: "A+", teacher_feedback: "Exceptional" },
        { name: "Science", score: 98, grade: "A+", teacher_feedback: "Future scientist" },
        { name: "English", score: 94, grade: "A+", teacher_feedback: "Creative writer" },
        { name: "Social Studies", score: 90, grade: "A+", teacher_feedback: "Well-rounded" },
      ],
      overall_percentage: 95.5,
      rank: "Top 1",
      attendance: "99%",
    },
  ],
  projects: [
    {
      id: "PROJ_001",
      title: "Solar Cooker Model",
      grade: "Grade 5",
      subject: "Science",
      description: "Built a functional solar cooker using recyclable materials that can reach temperatures up to 150°C.",
      skills_used: ["Creativity", "Scientific Thinking"],
      tools_used: ["Cardboard", "Aluminum Foil"],
      impact_metrics: ["Demonstrated to 50+ students", "Reduced cooking fuel usage conceptually"],
      reflection: "Learned how renewable energy can be applied in daily life.",
      mentor_feedback: "Outstanding creative thinking - Mrs. Verma",
      media: { images: [], videos: [], documents: [] },
      completion_date: "2021-01-10",
    },
    {
      id: "PROJ_002",
      title: "Water Purification System",
      grade: "Grade 6",
      subject: "Environmental Science",
      description: "Designed a low-cost water filtration prototype using sand, gravel, and activated charcoal layers.",
      skills_used: ["Problem Solving", "Research", "Engineering"],
      tools_used: ["PVC Pipes", "Sand", "Gravel", "Activated Charcoal"],
      impact_metrics: ["Presented at school science fair", "Won 1st place in school category"],
      reflection: "Understood water scarcity challenges and how simple solutions can make a big difference.",
      mentor_feedback: "Brilliant initiative addressing real-world problems - Mr. Rajan",
      media: { images: [], videos: [], documents: [] },
      completion_date: "2022-03-20",
    },
    {
      id: "PROJ_003",
      title: "AI Waste Sorter Concept",
      grade: "Grade 7",
      subject: "Technology",
      description: "Conceptualized an AI-powered waste sorting system with a Python prototype for image classification.",
      skills_used: ["Python", "AI/ML Concepts", "Design Thinking"],
      tools_used: ["Python", "Google Teachable Machine"],
      impact_metrics: ["Presented to school board", "Selected for district tech showcase"],
      reflection: "Combined programming skills with environmental passion to create a meaningful solution.",
      mentor_feedback: "Exceptional vision for technology in sustainability - Dr. Mehta",
      media: { images: [], videos: [], documents: [] },
      completion_date: "2023-02-15",
    },
  ],
  sports: [
    {
      sport_name: "Chess",
      role: "Team Captain",
      achievements: [
        { title: "Inter-School Chess Champion", level: "District", year: "2021", impact: "Trained 3 juniors to qualify for district level" },
        { title: "State Level Qualifier", level: "State", year: "2022", impact: "Represented school at state level" },
      ],
      skills_gained: ["Strategic Thinking", "Patience", "Focus"],
    },
    {
      sport_name: "Table Tennis",
      role: "Team Member",
      achievements: [
        { title: "School Champion", level: "School", year: "2023", impact: "Undefeated in school circuit" },
      ],
      skills_gained: ["Agility", "Quick Thinking", "Sportsmanship"],
    },
  ],
  extra_curriculars: [
    {
      category: "Debating",
      activity: "School Debate Club",
      role: "Speaker",
      achievements: ["Won 2nd place in inter-school debate", "Represented school in district MUN"],
      reflection: "Improved confidence and communication skills significantly.",
    },
    {
      category: "Arts",
      activity: "Painting",
      role: "Participant",
      achievements: ["Exhibited artwork in school annual day", "Won appreciation award for environmental art"],
    },
    {
      category: "Music",
      activity: "School Choir",
      role: "Vocalist",
      achievements: ["Performed at Independence Day celebration", "Participated in inter-school music festival"],
    },
  ],
  leadership_and_responsibility: [
    {
      title: "Class Monitor",
      grade: "Grade 6",
      responsibilities: ["Managed classroom discipline", "Coordinated with teachers"],
      impact: "Improved class punctuality by 20%",
    },
    {
      title: "Science Club President",
      grade: "Grade 7",
      responsibilities: ["Organized weekly experiments", "Mentored 15 junior members", "Arranged guest lectures"],
      impact: "Increased club membership by 40%",
    },
    {
      title: "Green Campus Ambassador",
      grade: "Grade 7",
      responsibilities: ["Led recycling initiatives", "Awareness campaigns"],
      impact: "Reduced campus paper waste by 30%",
    },
  ],
  certifications: [
    { title: "Basic Python Programming", platform: "Coursera", year: "2023", credential_id: "", verification_link: "" },
    { title: "Introduction to AI", platform: "Elements of AI", year: "2023", credential_id: "", verification_link: "" },
    { title: "Environmental Sustainability", platform: "Khan Academy", year: "2022", credential_id: "", verification_link: "" },
  ],
  job_ready_skills: {
    technical: ["Python", "MS Excel", "Basic Robotics", "Google Workspace", "Canva"],
    soft_skills: ["Leadership", "Communication", "Critical Thinking", "Teamwork", "Problem Solving"],
    languages: [
      { language: "English", proficiency: "Fluent" },
      { language: "Hindi", proficiency: "Fluent" },
      { language: "Kannada", proficiency: "Basic" },
    ],
  },
  impact_portfolio: [
    {
      title: "Community Cleanliness Drive",
      description: "Organized a local cleanliness campaign in the school neighborhood.",
      impact_metrics: ["Led a team of 10 students", "Collected 50kg waste", "Planted 20 saplings"],
      year: "2022",
    },
    {
      title: "Digital Literacy Workshop",
      description: "Conducted basic computer literacy sessions for underprivileged children.",
      impact_metrics: ["Trained 25 children", "3 sessions conducted", "100% attendance"],
      year: "2023",
    },
  ],
  analytics: {
    total_projects: 5,
    total_achievements: 12,
    leadership_roles: 3,
    hours_in_extracurriculars: 120,
  },
  verification: {
    school_verified: true,
    verified_by: [
      { name: "Mrs. Verma", role: "Science Teacher", contact: "", verification_note: "Consistently excellent performance" },
      { name: "Mr. Rajan", role: "Principal", contact: "", verification_note: "One of our most outstanding students" },
    ],
    parent_verified: true,
    certificates_uploaded: true,
    last_verified_date: "2024-03-01",
  },
  digital_presence: {
    portfolio_url: "",
    linkedin: "",
    github: "",
  },
};

export default studentData;
